### ISSUE TITLE
Schematic Capture

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#1]
Navjot - What issues did you face working with fritzing? How did you resolve them?

**Comment by Saininavjot** [comment]
There are various issues that I faced while working with fritzing software. I was learning this software and preparing schematic design for my project on this software:
 Issues that I faced while working with fritzing software are as follows:
1. Downloading and Installing Fritzing:
The latest version of fritzing is version 0.9.4, but this version is paid. However, I was looking for version that is free of cost. So, I downloaded fritzing version 0.9.3. But, it comes with its own cons. The version 0.9.3 does not have latest Microcontrollers like Beaglebone Black and latest interfacing modules. 
To resolve this issue: There is option in fritzing to import parts from online library of fritzing. This worked for me to work with fritzing version 0.9.3.
2. To find all part libraries:
The first step to prepare schematic design on fritzing version 0.9.3 is to check whether fritzing have all required part libraries or not. In parts window, I searched for all parts required to prepare schematic design. I was able to find almost all modules like ultrasonic sensor, Arduino Uno, LCD Display etc. However, two modules that I would not able to find was Beaglebone Black and ESP 8266. As, fritzing version 0.9.3 do not have all modules preinstalled in it. Firstly, I tried to customize these two modules on Fritzing using any general IC, but it was time consuming as I have to describe each pin of that IC with Beaglebone black pins. 
To resolve this issue: I tried to look for Fritzing parts library on internet specifically for Beaglebone black and ESP 8266. All the fritzing parts libraries have extension .fzpz. So, I looked specifically for beaglebone black with .fzpz extension file. I got this library on GitHub: https://github.com/adafruit/Fritzing-Library/blob/master/parts/BeagleBone%20Black.fzpz
Similarly, I got .fzpz file for ESP 8266 from link given below:
https://github.com/ydonnelly/ESP8266_fritzing/blob/master/ESP8266-12E%20WiFi%20Module.fzpz
3. Setting up grid size for all parts:
Some of the parts appear quite big and are not aligned to grid. The grid size of new parts is different from old parts.
To resolve this issue: In part editor of each part, in view option. We can change grid size for each component to 0.1 inch and there is also option to align part to the grid. So, all the parts in the schematic diagram are aligned to grid and set to grid size of 0.1 inch.
