### ISSUE TITLE
 interfacing the WiFi Module

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#12]
Ramneet - 1) What issues did you encounter when interfacing the WiFi Module? 2) How did you resolve them?

**Comment by embedded92** [comment]
While interfacing beaglebone with esp8266 I faced the problem that the Arduino platform for ESP only supports two UART and 2nd UART of ESP only supports TX. For our testing, I needed two UARTs as one is connected to beaglebone and 2nd is used for seeing the logs. 
I tried using UART 2 for seeing the logs, but it was not working properly. To resolve this I switched to using software UART which enables using any GPIO pins of ESP to be used as UART. I finally used D5 and D6 GPIO pin of ESP as RX and TX respectively and for this "SoftwareSerial.h" header file was used.
