### ISSUE TITLE
Interfacing the LCD Display to the BBB

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#16]
Navjot - 1) What issues did you face when Interfacing the LCD Display to the BBB? 2) How did you resolve them? 3) Why did not you use I2C protocol for communication? 4) Why are not you able to change the font size?

**Comment by Saininavjot** [comment]
Issues that I faced while interfacing LCD Display with BBB:
1. Interfacing Arduino Uno with BBB:
The GPIO pins of Beaglebone black are 3.3V and can be configured as inputs or outputs. The max output current varies by pin. For some pins it is 4mA and for some pins it is 6mA. The inputs are not 5V tolerant. The max voltage is 3.3V for GPIO pins. On the other hand, Input and output pins of Arduino Uno require operating voltage of 5V. If 5v signal is send back from Arduino Uno to BBB, it can destroy the Beaglebone board.
Resolving issue: Earlier, we thought of using Logic level convertor between Arduino and BBB. As logic level convertor converts 5v signal to 3.3v which is further given as input to the BBB. But, in our project, we do not require any acknowledgement of letters (data) received by Arduino back to BBB. We are not sending any data back to Beaglebone black. There is only transmission of data from BBB to receiver pin of Arduino. So, board is operated in safe conditions and our purpose is served as well.
2. Running code on Arduino IDE: When I tried to upload code into Arduino Board using Arduino IDE. It was showing error in code uploading and failed to upload the code. An error was displayed on the IDE. 
Resolving Issue: As Arduino Board was connected with Laptop using USB cable. The Arduino IDE was sending code to Arduino Board using USB protocol. Also, the receiver pin of the Arduino board was connected to transmission pin of BBB. As Arduino Board was receiving data from BBB using UART protocol. So, there was conflict between these data from Arduino IDE and BBB. So, we remove the receiver pin connection of Arduino Board with BBB while uploading code to the Arduino Board. When we tried to re-upload code into Arduino Uno, then problem was solved and uploading was done successfully.
3. Why did not you use I2C protocol for communication?
To interface the LCD with Beaglebone black using I2C protocol, we require extra PCF8574 expander module that support I2C communication with Beaglebone black. Some LCD have PCF module already attached to it. The LCD which we are using does not have this attached module to support I2C communication. So, we did not use I2C protocol for communication. Other option we were having is parallel communication between LCD and BBB in 4 bit mode or 8 bit mode. But, this require many GPIO pins of BBB to interface LCD in 4 bit mode or 8 bit mode. 
To resolve this issue: We made use of Arduino Uno as intermediate device between BBB and LCD Display. The Arduino Uno is interfaced with BBB using UART protocol and only one UART transmission pin is used of BBB as the data is only transmitted from BBB to Arduino Uno. The Arduino uno board is further interfaced with LCD Display using parallel communication in 4 bit mode.
4. Why are not you able to change the font size?
The LCD which we are using only supports font size of 5×8 dot matrix. We have looked for its specification from digikey site from where we ordered it and it was clearly mentioned on the website that it font size is 5×8 dot matrix. 
https://www.digikey.ca/en/products/detail/matrix-orbital/MOP-AL162A-BYFY-25J-3IN/9602838
