### ISSUE TITLE
Testing of components

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#2]
Ramneet - 1) What issues did you face with during testing the components? 2) How did you fix them?

**Comment by embedded92** [comment]
Following are the problems I faced while testing the Hardware Components of the project:

1.  To test LCD, I needed to use a potentiometer to adjust the contrast of the LCD screen. To adjust the potentiometer, it has a cross-head screw but I didn't have a cross-head screwdriver. The default setting of the potentiometer was set to min, which leads to no contrast on the LCD screen. First, I decided to use some resistance directly on the contrast pin, but it was taking more time to tune the contrast. Then while searching for some other components, I found an older potentiometer mixed with some resistors which have a slotted knob. Then I used that potentiometer to test the Lcd.

2.  Another issue I faced was a huge amount of inconsistency with the connections of the male jumper wires into the breadboard. For a long time, I thought I had bad components but later realized that it was the loose connections. Then few jumper wires were discarded and more attention was paid to these contacts.

3. Another problem that we faced was during the testing of the buzzer. While testing the buzzer, I observed that it is not beeping correctly, First I tried to check the connections to the buzzer, but they were correct and properly connected to the buzzer which led me to realize that the buzzer was faulty. I changed the buzzer to the spare buzzer and then it was working as expected.
