### ISSUE TITLE
Interfacing the ultra sonic

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#8]
Ramneet - 1) What issues did you face when interfacing the ultra sonic? 2) How did you resolve them?

**Comment by embedded92** [comment]
Issues that I faced while interfacing Ultrasonic sensors with Beaglebone black are as follows:

1. Issue: Ultrasonic sensor requires a 5v operating power supply. Firstly, I tried to power ultrasonic sensors from beaglebone onboard VDD power supply of 5v. But, when 0I tried running code on the terminal, there was no output from the ultrasonic sensor. I checked all the connections and code again, but still, the sensors were not operating.

Resolving this issue: I tried to find the underlying cause of this issue. One of the points that I get to know is that the Beaglebone black on board VDD pin only works if beaglebone is connected to power adaptor and getting constant 5 VDC, 2.5 A, barrel-plug supply. Another point I get to know is SYS 5v can be used if current drawn from the board by a sensor is under 500 m A. The SYS 5V pin can be used if Beaglebone black is powered by a USB cable. As, the ultrasonic sensor only draws 15 mA of current, so it is safe to use the SYS 5V pin to power beaglebone black.

https://cdn-shop.adafruit.com/datasheets/BBB_SRM.pdf

2. Issue: Earlier, in the code, I did not mention about range in centimeter within which ultrasonic sensor should detect obstacles. As in our project, the ultrasonic sensors' role is to detect the arrival and departure of the train, and sensors were placed just 3m to 4 cm away from the railway track. Earlier, this range was not specified. So, sensors were detecting any objects even from a far distance like walls, tables, etc.

Resolving this Issue: In the code, I mentioned about specific range within which sensors should detect train. If the distance is between 4 and 6 cm, then only the sensor will detect that object like a train.

if ( distance>= 4 && distance =< 6)
            {
                        printf("train arriving......\r\n");
                        printf("Distance= %d \r\n", distance);
                        printf("\r\n", distance);
            }

3. Issue: Earlier, I did not get the perfect library to access the GPIO pins of Beaglebone Black. There are few general libraries that can be used for any processor for accessing GPIO pins. But, I was not able to find specifically for beaglebone black.

Resolving this Issie:
I come across the specific library for beaglebone black, i.e., IOBB library at GitHub:

https://github.com/shabaz123/iobb

There were few steps to be followed while installing and downloading IOBB library.
1.         mkdir development 
2.         cd development 
3.         git clone https://github.com/shabaz123/iobb.git 
4.         cd iobb 
5.         make 
6.         make install
