### ISSUE TITLE
Interfacing stepper motor with BeagleBone Black

### ISSUE THREAD

**Issue by mikeshams** [Saininavjot/Capstone-Project-Group-1#9]
Navjot - What issues did you face when Interfacing stepper motor with BeagleBone Black? How did you resolve them?

**Comment by Saininavjot** [comment]
**Issues that I faced while interfacing stepper motor with BBB are as follows:**
**1. Writing C code for stepper motor:**
Programming stepper motor was bit challenging for us as we have to rotate motor in clockwise of anticlockwise direction using GPIO pins of Beaglebone Black. Programming stepper motor is not as easy as DC motor. Here, we have to configure step size and number of steps to be taken by motor to rotate at particular angle. First challenge was toprogram stepper motor for  90 degree rotation and we require knowledge about its basic functionality. . We write the C code for stepper motor, but while running the code on linux terminal, motor was not responding. There was some issue in the code.
**Resolving this issue:** All the connections were fine but code was not working as per requirement to rotate the motor. Then, we researched about functioning of stepper motor and we get to know some basic details about motor such as how to calculate number of steps from step angle. Secondly, it is important to decide whether to use 4 step sequence or 8 step sequence to rotation of motor. 
We decided to go with 4 step sequence,  that means combination of wires are as follows:
AB-BC-CD-DA
In the code, 4 GPIO pins were initialized as A, B, C, D input from BBB. In actual code, the data 1 or 0 was written to these pins. A, B, C, D were considered as input wires to stepper motor. 
- This link provide us with basic understanding to program stepper motor in 4 step sequence
https://www.instructables.com/BYJ48-Stepper-Motor/ 

-  This link helps us to write C code for stepper motor interfacing with Beaglebone Black.
https://bwgz57.wordpress.com/2012/04/03/beaglebone-stepping-out/    
To calculate number of steps for 90 degree rotation in 4 step sequences, the formula used is as follows:
 Steps = Number of steps in One Revolution * Gear ratio = 32*64 = 2048
To rotate by 90 degree: 2048/4 = 512

**2. Appropriate power supply:** 
The second issue is to power ULN2003 driver from appropriate power source. ULN2003 driver further power stepper motor with required voltage and current. Earlier, we powered ULN2003 driver from Beaglebone Black 5v on board pin. But, powering high current motor from Beaglebone Black can result in destruction of Microcontroller. So, we need some alternative so as to make sure that Beaglebone is operated in safe condition without its failure.
**To resolve this issue:** We decided to use external power module for power our ULN2003 driver. So, we used adjustable power module that can provide power from range 3.3V to 12 V to any device that is operated in this range. This power module is further connected to power adaptor. The power module provide 5V power supply to driver circuit as well as appropriate current of 500 mA.
